import Head from "next/head";
import Header from "../layout/header/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      <Head>
        <title>NKTW Ecommerce | NKTW</title>
        <meta name="description" content="NKTW Ecommerce | NKTW" key="desc" />
      </Head>
      <Header />
      <div style={{ maxWidth: "1024px", margin: "auto" }}>{children}</div>
    </>
  );
}
